---
title: "Construct proliferation: Overall"
output: 
  word_document: 
    keep_md: true
---


```{r setup, include=FALSE}
library(groundhog)
groundhog.library(c("tidyverse", "knitr", "xfun"), 
                  date = "2024-02-24")
library(knitr)
opts_chunk$set(echo = TRUE, error = T, warning = F, message = F)

theme_set(theme_minimal(base_size = 14))

set.seed(20191005)
```



```{r}
records_wide <- readRDS("../sober_rubric/raw_data/preprocessed_records.rds")
psyctests_info <- readRDS("../sober_rubric/raw_data/psyctests_info.rds")
psyctests_info <- psyctests_info %>% 
  left_join(records_wide %>% select(DOI, Acronym = first_acronym), by = "DOI") %>% 
  mutate(shortName = coalesce(Acronym, Name)) %>% 
  mutate(shortName = case_when(
    Name == "trail making test" ~ "TMT",
    Name == "alcohol use disorders identification test" ~ "AUDIT",
    Name == "perceived stress scale" ~ "PSS",
    Name == "perceived stress scale" ~ "PSS",
    Name == "beck anxiety inventory" ~ "BAI",
    Name == "positive and negative affect scale" ~ "PANAS-B",
    Name == "center for epidemiological studies depression scale" ~ "CESD",
    Name == "stroop color and word test" ~ "SCWT",
    Name == "clinician-administered ptsd scale" ~ "CAPS",
    shortName == "WHO WMH-CIDI" ~ "WMH-CIDI",
    Name == "barthel index" ~ "ADL",
    Name == "stroop color and word test" ~ "SCWT",
    TRUE ~ shortName
  ))
```

## By subdiscipline
```{r}
psyctests_info %>% group_by(subdiscipline_1, DOI, shortName, Name) %>%
  summarise(usage_count = sum(usage_count, na.rm = T)) %>% 
  ungroup() %>% 
  arrange(desc(usage_count)) %>% 
  head(50) %>% 
  kable()
```

## By subdiscipline (2015-2023)
```{r}
psyctests_info %>% group_by(subdiscipline_1, DOI, shortName, Name) %>%
  filter(Year > 2015) %>% 
  summarise(usage_count = sum(usage_count, na.rm = T)) %>% 
  ungroup() %>% 
  arrange(desc(usage_count)) %>% 
  head(50) %>% 
  kable()
```

## By type 
```{r}
psyctests_info %>% group_by(instrument_type_broad, DOI, shortName, Name) %>%
  summarise(usage_count = sum(usage_count, na.rm = T)) %>% 
  ungroup() %>% 
  arrange(desc(usage_count)) %>% 
  head(50) %>% 
  kable()
```


## By type (2015-2023)
```{r}
psyctests_info %>% group_by(instrument_type_broad, DOI, shortName, Name) %>%
  filter(Year > 2015) %>% 
  summarise(usage_count = sum(usage_count, na.rm = T)) %>% 
  ungroup() %>% 
  arrange(desc(usage_count)) %>% 
  head(50) %>% 
  kable()
```
